name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install project dependecies
        run: npm install
      - name: Decrypt large secrets
        run: ./.github/scripts/decrypt.sh
        env:
          PASS: ${{ secrets.GPG_KEY }}
      - name: Update project credentials
        run: ./.github/scripts/update_credentials.sh
        env:
          MAPS_SDK_API_KEY: ${{ secrets.MAPS_SDK_API_KEY }}
          GOOGLE_SIGN_IN_WEB_CLIENT_ID: ${{ secrets.GOOGLE_SIGN_IN_WEB_CLIENT_ID }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
      - name: Build Application
        working-directory: ./android
        run: |
          ls -l ./app
          ./gradlew assembleRelease
          ls ./app/build/outputs/apk/release/
