name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install
      - run: gpg2 --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_SERVICES_KEY }}" --output android/app/google-services.json android/app/google-services.json.gpg
      - run: sed s/MAPS_SDK_API_KEY/${{ secrets.MAPS_SDK_API_KEY }}/g android/app/src/main/AndroidManifest.xml
      - run: sed s/GOOGLE_SIGN_IN_WEB_CLIENT_ID/${{ secrets.GOOGLE_SIGN_IN_WEB_CLIENT_ID }}/g screens/SignInScreen/index.js screens/SignUpScreen/index.js
      - working-directory: ./android
        run: |
          pwd
          ls -l
          chmod +x ./gradlew
          ./gradlew assembleRelease
          ls ./app/build/outputs/apk/release/
